### ISSUE TITLE
In rare instances, synced-cron can crash if polling once per minute

### ISSUE THREAD

**Issue by ryangrahamnc** [percolatestudio/meteor-synced-cron#133]
I've got a cron that runs once per minute. And in the rare case where I start the server at the very end of one minute (like at `11:00:59.950`), I eventually get an error of `E11000 duplicate key error collection`. I believe this is because the calculation of `intendedAt` can be the same for two minutes in the row based on millisecond delays in processing.

Here's some relevant code:
```
SyncedCron.add({
    name: 'Poll for change request updates',
    schedule: function(parser){
        return parser.text('every 1 minute');
    },
    job: async function(){
        var result;
        try{
            result = await poll();
        }
        catch(err){
            log.error({ err }, 'failed to poll');
        }
        return result;
    },
});
SyncedCron.start();
```

And here are logs for when the error happened:
```
I20180607-11:18:00.004(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:18:00.005(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:19:00.006(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:19:00.007(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:20:00.004(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:20:00.005(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:21:00.006(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:21:00.007(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:22:00.004(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:22:00.005(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:23:00.005(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:23:00.006(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:24:00.003(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:24:00.004(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:25:00.012(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:25:00.013(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:26:00.001(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:26:00.002(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:26:59.952(-4) (percolate_synced-cron.js:87) SyncedCron: Starting "Poll for change request updates".
I20180607-11:26:59.953(-4) (percolate_synced-cron.js:87) SyncedCron: Finished "Poll for change request updates".
I20180607-11:27:00.007(-4)? Exception in setTimeout callback: { WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: meteor.cronHistory index: intendedAt_1_name_1 dup key: { : new Date(1528385220000), : \"Poll for change request updates\" }","op":{"intendedAt":"2018-06-07T15:27:00.000Z","name":"Poll for change request updates","startedAt":"2018-06-07T15:27:00.003Z","_id":"LPmxbLtJmbiieLX5N"}})
I20180607-11:27:00.007(-4)?     at resultHandler (/Users/rmgraham/.meteor/packages/npm-mongo/.3.0.7.f360qz.y7s7++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:459:11)
I20180607-11:27:00.007(-4)?     at /Users/rmgraham/.meteor/packages/npm-mongo/.3.0.7.f360qz.y7s7++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:544:18
I20180607-11:27:00.007(-4)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20180607-11:27:00.008(-4)?     at process._tickCallback (internal/process/next_tick.js:180:9)
I20180607-11:27:00.029(-4)?   name: 'BulkWriteError',
I20180607-11:27:00.029(-4)?   message: 'E11000 duplicate key error collection: meteor.cronHistory index: intendedAt_1_name_1 dup key: { : new Date(1528385220000), : "Poll for change request updates" }',
I20180607-11:27:00.029(-4)?   driver: true,
I20180607-11:27:00.029(-4)?   code: 11000,
I20180607-11:27:00.029(-4)?   index: 0,
I20180607-11:27:00.029(-4)?   errmsg: 'E11000 duplicate key error collection: meteor.cronHistory index: intendedAt_1_name_1 dup key: { : new Date(1528385220000), : "Poll for change request updates" }',
I20180607-11:27:00.030(-4)?   getOperation: [Function],
I20180607-11:27:00.030(-4)?   toJSON: [Function],
I20180607-11:27:00.030(-4)?   toString: [Function],
I20180607-11:27:00.030(-4)?   result: 
I20180607-11:27:00.030(-4)?    BulkWriteResult {
I20180607-11:27:00.030(-4)?      ok: [Getter],
I20180607-11:27:00.030(-4)?      nInserted: [Getter],
I20180607-11:27:00.030(-4)?      nUpserted: [Getter],
I20180607-11:27:00.031(-4)?      nMatched: [Getter],
I20180607-11:27:00.031(-4)?      nModified: [Getter],
I20180607-11:27:00.031(-4)?      nRemoved: [Getter],
I20180607-11:27:00.031(-4)?      getInsertedIds: [Function],
I20180607-11:27:00.031(-4)?      getUpsertedIds: [Function],
I20180607-11:27:00.031(-4)?      getUpsertedIdAt: [Function],
I20180607-11:27:00.031(-4)?      getRawResponse: [Function],
I20180607-11:27:00.031(-4)?      hasWriteErrors: [Function],
I20180607-11:27:00.031(-4)?      getWriteErrorCount: [Function],
I20180607-11:27:00.032(-4)?      getWriteErrorAt: [Function],
I20180607-11:27:00.032(-4)?      getWriteErrors: [Function],
I20180607-11:27:00.032(-4)?      getLastOp: [Function],
I20180607-11:27:00.032(-4)?      getWriteConcernError: [Function],
I20180607-11:27:00.032(-4)?      toJSON: [Function],
I20180607-11:27:00.032(-4)?      toString: [Function],
I20180607-11:27:00.032(-4)?      isOk: [Function] } }
```
Notice the timestamp of `11:26:59.952` right before the crash.
The end result is the synced cron stops running.

One possible "solution" would be to remove the unique constraint on the `intendedAt_1_name_1` index.

**Comment by ryangrahamnc** [comment]
Update: Since this package isnt supported anymore, we switched over to using a kube cron instead

**Comment by fhackenb** [comment]
I was seeing this too and it appears to be fixed now. I just needed to run `meteor remove percolate:synced-cron && meteor add littledata:synced-cron`
