### ISSUE TITLE
Synced Cron stopped working

### ISSUE THREAD

**Issue by WayneUong** [percolatestudio/meteor-synced-cron#99]
Synced Cron just stopped working entirely. Only these errors are in the logs:

```
Exception in setTimeout callback: MongoError: driver is incompatible with this server version
[52.39.101.171]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:420:15)
    at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
[52.39.101.171]     at MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:736:49)
    at MongoConnection.mongoConnectionProto.(anonymous function) [as insert] (packages/meteorhacks_kadira/lib/hijack/db.js:62:1)
[52.39.101.171]     at OptimizedApply (packages/meteorhacks_kadira/lib/utils.js:31:1)
    at Object.ret.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:20:1)
[52.39.101.171]     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/insert.js:48:1)
    at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
[52.39.101.171]     at [object Object].insert (packages/mongo/collection.js:507:37)
    at packages/percolate_synced-cron/synced-cron-server.js:203:1
[52.39.101.171]     at scheduleTimeout (packages/percolate_synced-cron/synced-cron-server.js:266:1)
    at packages/percolate_synced-cron/synced-cron-server.js:314:1
[52.39.101.171]     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
[52.39.101.171]     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    - - - - -
[52.39.101.171]     at Object.toError (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
[52.39.101.171]     at Object.__executeInsertCommand [as executeInsertCommand] (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1926:27)
    at [object Object].execute_writes (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:133:15)
[52.39.101.171]     at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/ha.js:201:41
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
[52.39.101.171]     at Server.Base._callHandler (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
[52.39.101.171]     at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
[52.39.101.171]     at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
[52.39.101.171]     at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.emit (events.js:95:17)
[52.39.101.171]     at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)

```

**Comment by kamil7732** [comment]
are you sure it's this package problem? I see meteorhacks_kadira, matb33_collection-hooks between the  method call from this package and the error you get

**Comment by WayneUong** [comment]
This is the only error I saw in the log. I guess it might have to do with us using mongo 3.2 thus the incompatible driver. I schedule a job to clear completed jobs in cronHistory regularly, and the error hasn't appeared again. Is there anything wrong with this solution?

**Comment by tomtom87** [comment]
`Exception in setTimeout callback: MongoError: driver is incompatible with this server version`

Please use a compatible mongo to fix this issue
